### ISSUE TITLE
Duplicate

### ISSUE THREAD

**Issue by vipulasri** [anoop44/AwesomeTextInputLayout#1]
This feature or custom behavior is already there in [Material Components](https://github.com/material-components/material-components-android). 

You can use "Outlined Box", from [here](https://material.io/develop/android/components/text-input-layout/)

P.S: My concern why re-inventing the wheel and there will be lot of edge cases that must have already been addressed in Material Components.

**Comment by anoop44** [comment]
@vipulasri Yeah, I saw that property after building this.

**Comment by akshay-nayak** [comment]
Hey anoop yours is better and less complex than material design . Cheers!!!
