### ISSUE TITLE
Label size when focus?

### ISSUE THREAD

**Issue by newbie1992** [anoop44/AwesomeTextInputLayout#2]
How to change the hint size when focus?

**Comment by anoop44** [comment]
You can use `animatedTextSize` property in xml. Sorry I forgot to add it in README. Let me know if that works for you

**Comment by newbie1992** [comment]
Thanks, that solve my problem but I had another issues, how to set the border width between the label when focus on it, now the label text is overlay on the border.

**Comment by anoop44** [comment]
I have pushed a fix for the overlapping issue. Available in version`1.0.1`
