### ISSUE TITLE
The label text is overlay on the border.

### ISSUE THREAD

**Issue by franfdezmorales** [anoop44/AwesomeTextInputLayout#5]
First of all, thank you for that amazing library. 
I found a bug, it happens when u hide the keyboard.

https://gyazo.com/6c8ce2adaad9df20153c6362aec11c29

**Comment by anoop44** [comment]
@OverloadFran I hope you are using the latest version of the library. I will try to reproduce and fix it

**Comment by franfdezmorales** [comment]
@anoop44 Yeah, im using the version 1.0.2 Thank your for your fast response.

**Comment by anoop44** [comment]
@OverloadFran 1.0.3 has been released. Try it out and see if it fixes your issue

**Comment by franfdezmorales** [comment]
@anoop44 Thank you one more time for your fast response. I tried but now when you hide the keyboard, the placeholder and the label hide too.
 https://gyazo.com/549286d84dc53140cede9a65156d6f5e

**Comment by franfdezmorales** [comment]
Trying thing with the widht and the height it works correctly now. Thank you a lot! Im really appreciated.

**Comment by anoop44** [comment]
Closing the issue
